[package]
name = "juno"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ignore = "0.4.22"
prost = "0.12.4"
tokio = { version = "1", features = ["full"] }
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
