syntax = "proto3";

package juno;

service JunoServices {
  rpc Ping (EmptyRequest) returns (PingResponse);
  rpc GetFiles (GetFilesRequest) returns (GetFilesResponse);
  rpc SkipSong (EmptyRequest) returns (EmptyResponse);
  rpc Play (EmptyRequest) returns (EmptyResponse);
  rpc Pause (EmptyRequest) returns (EmptyResponse);
  rpc PlayPause (EmptyRequest) returns (EmptyResponse);
}

enum Status {
  SUCCESS = 0;
  ERROR = 1;
}

message EmptyRequest {
}

message EmptyResponse {
}

message PingResponse {
  string message = 1;
}

message GetFilesRequest {
  string path = 1;
}

message GetFilesResponse {
  repeated string files = 1;
}
